steps:
# 1. Build container (from app directory)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:latest', '../../app']
  dir: 'Development'

# 2. Initialize Terraform
- name: 'hashicorp/terraform'
  args: ['init']
  dir: 'Development'

# 3. Apply changes
- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve']
  dir: 'Development'

options:
  logging: CLOUD_LOGGING_ONLY