steps:
- name: 'hashicorp/terraform'
  args: ['init']
  dir: 'Development'  # Points to your exact folder

- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve']
  dir: 'Development'  # Points to your exact folder

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
timeout: 1200s