steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:latest', '/workspace/app']
  timeout: 600s

- name: 'hashicorp/terraform'
  args: ['init']
  dir: '/workspace/Development'
  timeout: 300s

- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve']
  dir: '/workspace/Development'
  timeout: 1200s  # 20 minute timeout
  env:
  - 'TF_VAR_project_id=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
  timeout: 1800s  # Overall 30 minute timeout