steps:
  - name: 'hashicorp/terraform:1.5.7'
    args: ['init']
    dir: 'Development'
    

  - name: 'hashicorp/terraform:1.5.7'
    args: ['plan']
    dir: 'Development'
    waitFor: ['init']

  - name: 'hashicorp/terraform:1.5.7'
    args: ['apply', '-auto-approve']
    dir: 'Development'
    waitFor: ['plan']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
timeout: 1200s