steps:
# 1. Build container (note the path)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:latest', '${_APP_PATH}']
  
# 2. Terraform steps
- name: 'hashicorp/terraform'
  args: ['init']
  
- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _APP_PATH: ../app  # Critical change