steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/welcome-app:latest', '.']
  
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/welcome-app:latest']
  
  # Terraform init
  - name: 'hashicorp/terraform:1.5.7'
    args: ['init']
    id: 'init'

  # Terraform plan
  - name: 'hashicorp/terraform:1.5.7'
    args: ['plan']
    id: 'plan'
    waitFor: ['init']

  # Terraform apply
  - name: 'hashicorp/terraform:1.5.7'
    args: ['apply', '-auto-approve']
    id: 'apply'
    waitFor: ['plan']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
timeout: 1200s

substitutions:
  _TERRAFORM_VERSION: "1.5.7"