steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:latest', '/workspace/app']

- name: 'hashicorp/terraform'
  args: ['init']
  dir: '/workspace/Development'

- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve']
  dir: '/workspace/Development'

options:
  logging: CLOUD_LOGGING_ONLY