steps:
  # First copy all files to /workspace
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/your-repo.git', '.']
    waitFor: ['-']
  
  # Then change to Development directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/welcome-app:latest', '-f', 'app/Dockerfile', 'app']
    dir: 'Development'
    id: 'docker-build'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/welcome-app:latest']
    dir: 'Development'
    waitFor: ['docker-build']
  
  - name: 'hashicorp/terraform:1.5.7'
    args: ['init']
    dir: 'Development'
    id: 'terraform-init'
  
  - name: 'hashicorp/terraform:1.5.7'
    args: ['plan']
    dir: 'Development'
    id: 'terraform-plan'
    waitFor: ['terraform-init']
  
  - name: 'hashicorp/terraform:1.5.7'
    args: ['apply', '-auto-approve']
    dir: 'Development'
    id: 'terraform-apply'
    waitFor: ['terraform-plan']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
timeout: 1200s