steps:
# 1. Build container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:latest', './app']

# 2. Deploy infrastructure
- name: 'hashicorp/terraform'
  args: ['init']
  
- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve']

options:
  logging: CLOUD_LOGGING_ONLY